### ISSUE TITLE
Change repo name from firefox-svg-icons to firefox-icons

### ISSUE THREAD

**Issue by brassy-** [FirefoxUX/firefox-icons#11]
This repo is going to contain not only SVG but also different kind of format according to the platform. So having SVG in the name doesn't make sense anymore.

**Comment by nt1m** [comment]
@brassy- Or just "Icons" ? Since the owner is FirefoxUX.

**Comment by brassy-** [comment]
@nt1m I'm still advocating for `firefox-icons`. If someone forks the repo, it still keeps the right context

**Comment by nt1m** [comment]
Sounds good then.

**Comment by bwinton** [comment]
And it's done.

**Comment by nt1m** [comment]
@bwinton, can you update the github description as well ? it seems to link to the old URL

**Comment by bwinton** [comment]
Done.  Good catch!  🙂
