### ISSUE TITLE
Add a deprecated category and upoad new photon icons

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/firefox-icons#12]
- [x] Add a deprecated category
- [x] Move the current icons into deprecated
- [x] Add the photon new icons

**Comment by nt1m** [comment]
Where can I find the photon assets ?

**Comment by aminalhazwani** [comment]
I will PR a first batch of photony icons in the upcoming days! 😄

**Comment by brassy-** [comment]
I open a PR for this issue.

**Comment by brassy-** [comment]
On #15 
> I'm just wondering if the DevTools icons should be deprecated though. Or is there a plan to make new photon-style icons for DevTools?

Yes, the plan is to align all Firefox products (including DevTools) with the **new style**.

 I noticed now in the viewer we display the deprecated icons (good) but not the new one (bad). 

How so?
