### ISSUE TITLE
Figure out why caching isn't working

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/firefox-icons#14]
For some reason, caching no longer works, which means we quickly reach Github's API rate. I know it used to work before though.

**Comment by nt1m** [comment]
@bwinton I'm guessing the build steps you're adding will get rid of the API requests ?

**Comment by bwinton** [comment]
Well, I removed the code that did the caching, but I also removed the code that calls Github's API, so this shouldn't be an issue anymore.

**Comment by nt1m** [comment]
@bwinton Have you pushed those changes yet ? I don't see that code being removed.

**Comment by bwinton** [comment]
They should be both on master and on hh-pages…

**Comment by nt1m** [comment]
@bwinton The build code is definitely there, but the viewer still seems to use the github api.

**Comment by bwinton** [comment]
Hmm.  I'll look at it tomorrow or Monday.
